splice by Yevhen Sahach
mate-academy/js_array-method-splice pull request #16
Opened 2019-09-01 08:58 UTC by yevhen-sahach

2019-09-03 08:27 UTC, irenhh requested changes

2019-09-03 08:27 UTC, irenhh commented on src/arrayMethodSplice.js
> +        ? start
don't nest ternary operator, apply default values for arguments

2019-09-03 08:27 UTC, irenhh commented on src/arrayMethodSplice.js
> +    const deleteCount = del === undefined
the same

2019-09-05 08:14 UTC, yevhen-sahach commented on src/arrayMethodSplice.js
> +    const deleteCount = del === undefined
It doesn't make sense here

2019-09-06 14:39 UTC, irenhh approved these changes

2023-01-14 15:23 UTC, closed without merging